on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
            
      - uses: actions/checkout@v3
      - name: "Login to doker hub"
        run: docker login --username ${{ secrets.DOKER_USERNAME }} --password ${{ secrets.DOKER_TOKEN }}